### ISSUE TITLE
The category selection of the sythesis from old classes

### ISSUE THREAD

**Issue by yifliu3** [Jun-CEN/Open_world_3D_semantic_segmentation#7]
Thanks for sharing your great work!

I'm a little confused about the category selection of the synthesis procedure. As described in your paper,  the old classes used to synthesize novel objects are car for SemanticKITTI and car, bus, and truck for nuScenes, so what is the basis of this selection strategy?

**Comment by Jun-CEN** [comment]
Hi,

The only requirement of old classes used for synthesize novel objects is that the chosen class should belong to 'thing' class not 'stuff', so that we have the instance IDs of objects and use them for synthesize. For different datasets, we do not have additional reasons or bias, we just pick them.
